#!/usr/bin/env python3
"""Generate preview.svg from preview.src.svg by converting its text to outlines.

Why not just run inkscape over the whole card: inkscape rewrites the ENTIRE
document, reformatting the mark's path data (absolute/relative, decimal
precision). That would make the committed card's geometry differ textually from
logo.svg and icon.svg, and the build's drift check greps for exact geometry. So
each <text> is outlined in ISOLATION and spliced back into the source, leaving
every other byte of the card untouched.
"""

import os
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "preview.src.svg")
DST = os.path.join(HERE, "preview.svg")

SVG_NS = "http://www.w3.org/2000/svg"
TEXT_RE = re.compile(r"[ \t]*<text\b.*?</text>\s*?\n", re.S)
ROOT_RE = re.compile(r"<svg\b[^>]*>", re.S)
SKIP = {"defs", "metadata", "namedview", "title"}


def outline_one(text_el, root_open, tmp):
    """Outline a single <text> element, preserving its absolute placement."""
    src = os.path.join(tmp, "t.svg")
    out = os.path.join(tmp, "t-out.svg")
    with open(src, "w") as f:
        f.write(f"{root_open}\n{text_el}\n</svg>\n")
    subprocess.run(
        ["inkscape", src, "--export-text-to-path", "--export-plain-svg", "-o", out],
        check=True,
        capture_output=True,
    )
    # Parse rather than pattern-match: inkscape emits self-closing <path/> with
    # attributes spread over several lines, which a naive regex silently misses.
    ET.register_namespace("", SVG_NS)
    root = ET.parse(out).getroot()
    shapes = []
    for child in root:
        tag = child.tag.split("}")[-1]
        if tag in SKIP:
            continue
        # Drop inkscape's editor bookkeeping, keep the drawing and its a11y label.
        for attr in list(child.attrib):
            if attr.startswith("{http://www.inkscape.org") or attr.startswith("{http://sodipodi"):
                del child.attrib[attr]
        child.attrib.pop("id", None)
        shapes.append(ET.tostring(child, encoding="unicode").strip())
    if len(shapes) != 1:
        raise SystemExit(f"outline: expected 1 shape from a text element, got {len(shapes)}")
    return re.sub(r'\s+xmlns(:\w+)?="[^"]*"', "", shapes[0])


def main():
    with open(SRC) as f:
        src = f.read()

    texts = TEXT_RE.findall(src)
    if len(texts) != 2:
        raise SystemExit(f"outline: expected 2 <text> elements in preview.src.svg, found {len(texts)}")
    root_open = ROOT_RE.search(src).group(0)

    out = src
    with tempfile.TemporaryDirectory() as tmp:
        for text_el in texts:
            shape = outline_one(text_el.strip(), root_open, tmp)
            shape = "\n".join("  " + ln if ln.strip() else ln for ln in shape.splitlines())
            out = out.replace(text_el, shape + "\n", 1)

    banner = (
        "  <!-- GENERATED by ./build.sh -outline from preview.src.svg. Do not hand\n"
        "       edit: the next outline run overwrites it. Text is outlined so the\n"
        "       build needs no installed font; edit the copy in preview.src.svg. -->\n"
    )
    out = out.replace(root_open + "\n", root_open + "\n" + banner, 1)

    with open(DST, "w") as f:
        f.write(out)
    print(f"outlined 2 text elements -> {os.path.relpath(DST, os.getcwd())}")


if __name__ == "__main__":
    sys.exit(main())
